// <auto-generated />
using System;
using JustoNovo.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustoNovo.Infrastructure.Migrations
{
    [DbContext(typeof(JustoDbContext))]
    partial class JustoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Advogado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Oab")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Oab");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Advogado");

                    b.ToTable("Advogado", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.AdvogadoEspecialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvogadoId")
                        .HasColumnType("int");

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("atualizadopor");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("cadastradopor");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("NomeAreaDireito")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("NomeAreaDireito");

                    b.HasKey("Id")
                        .HasName("PK_AdvogadosEspecialidades");

                    b.HasIndex("AdvogadoId");

                    b.ToTable("AdvogadosEspecialidades", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenciaBancaria")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("AgenciaBancaria");

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<string>("Banco")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Banco");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<string>("CertificadoReservista")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("CertificadoReservista");

                    b.Property<string>("Cnh")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Cnh");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Cnpj");

                    b.Property<string>("CodClt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComprovanteDeResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contato")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Contato");

                    b.Property<string>("ContratoSocialCliente")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ContratoSocialCliente");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("EstadoCivil");

                    b.Property<string>("Genero")
                        .HasMaxLength(13)
                        .HasColumnType("varchar")
                        .HasColumnName("Genero");

                    b.Property<string>("NIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nacionalidade");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacao")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Ocupacao");

                    b.Property<string>("PisPasep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("ProcuracaoRepresentacaoLegal")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("ProcuracaoRepresentacaoLegal");

                    b.Property<string>("Renda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReuAutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasMaxLength(9)
                        .HasColumnType("varchar")
                        .HasColumnName("Rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Telefone");

                    b.Property<string>("Tipo")
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .HasColumnName("Tipo");

                    b.HasKey("Id")
                        .HasName("PK_Clientes");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[EnderecoId] IS NOT NULL");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Bairro");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("Cep");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Municipio");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("Numero");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("Referencia");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Rua");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar")
                        .HasColumnName("UF");

                    b.HasKey("Id")
                        .HasName("PK_Endereco");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Polo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<string>("CPFAdvogado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("CPFAdvogado");

                    b.Property<string>("CPFCNPJParte")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("CPFCNPJParte");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("NomeAdvogado")
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("NomeAdvogado");

                    b.Property<string>("NomeParte")
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("NomeParte");

                    b.Property<string>("OAB")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("OAB");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessoId");

                    b.Property<string>("TipoParte")
                        .HasMaxLength(9)
                        .HasColumnType("varchar")
                        .HasColumnName("TipoParte");

                    b.HasKey("Id")
                        .HasName("PK_Polo");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Polo", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvogadaCiente")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("AdvogadaCiente");

                    b.Property<int?>("AdvogadoId")
                        .HasColumnType("int")
                        .HasColumnName("AdvogadoId");

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<string>("Autuacao")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Autuacao");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<string>("CodPJEC")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("CodPJEC");

                    b.Property<string>("Comarca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Comarca");

                    b.Property<string>("Competencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Competencia");

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAbertura");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataFim");

                    b.Property<string>("JusGratis")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("JusGratis");

                    b.Property<string>("MeioDeComunicacao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("MeioDeComunicacao");

                    b.Property<DateTime?>("MeioDeComunicacaoData")
                        .HasColumnType("datetime2")
                        .HasColumnName("MeioDeComunicacaoData");

                    b.Property<string>("MotivosProcesso")
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("MotivosProcesso");

                    b.Property<string>("ObsProcesso")
                        .HasMaxLength(400)
                        .HasColumnType("varchar")
                        .HasColumnName("ObsProcesso");

                    b.Property<string>("OrgaoJulgador")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("OrgaoJulgador");

                    b.Property<string>("PJECAcao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("PJECAcao");

                    b.Property<string>("PartesProcesso")
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("PartesProcesso");

                    b.Property<string>("Prazo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Prazo");

                    b.Property<string>("Prioridade")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("Prioridade");

                    b.Property<string>("ProximoPrazo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ProximoPrazo");

                    b.Property<string>("ProximoPrazoData")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ProximoPrazoData");

                    b.Property<string>("SegredoJustica")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("SegredoJustica");

                    b.Property<string>("TituloProcesso")
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("TituloProcesso");

                    b.Property<string>("TutelaLiminar")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("TutelaLiminar");

                    b.Property<string>("UltimaMovimentacaoProcessual")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("UltimaMovimentacaoProcessual");

                    b.Property<DateTime?>("UltimaMovimentacaoProcessualData")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimaMovimentacaoProcessualData");

                    b.Property<string>("ValorDaCausa")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ValorDaCausa");

                    b.HasKey("Id")
                        .HasName("PK_Processo");

                    b.HasIndex("AdvogadoId");

                    b.HasIndex("CodPJEC")
                        .IsUnique();

                    b.ToTable("Processos", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.ProcessosAtualizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<string>("CodPJEC")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("CodPJEC");

                    b.Property<string>("ConteudoAtualizacao")
                        .HasMaxLength(400)
                        .HasColumnType("varchar")
                        .HasColumnName("ConteudoAtualizacao");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<DateOnly?>("DataMovimentacao")
                        .HasColumnType("date")
                        .HasColumnName("DataMovimentacao");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessoId");

                    b.Property<string>("TituloMovimento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("TituloMovimento");

                    b.HasKey("Id")
                        .HasName("PK_ProcessosAtualizacao");

                    b.HasIndex("ProcessoId");

                    b.ToTable("ProcessosAtualizacao", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.ProcessosCompromissos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<DateTime>("DataProximoEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataProximoEvento");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Local");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("NomeAdvogado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("NomeAdvogado");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("NomeCliente");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar")
                        .HasColumnName("Obs");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Prioridade");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessoId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("PK_ProcessosCompromissos");

                    b.HasIndex("ProcessoId");

                    b.ToTable("ProcessosCompromissos", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.SiteContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnalisadoContato")
                        .HasColumnType("bit")
                        .HasColumnName("AnalisadoContato");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Assunto");

                    b.Property<int>("AtualizadoPor")
                        .HasColumnType("int")
                        .HasColumnName("AtualizadoPor");

                    b.Property<int>("CadastradoPor")
                        .HasColumnType("int")
                        .HasColumnName("CadastradoPor");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar")
                        .HasColumnName("Conteudo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Telefone");

                    b.Property<string>("TipoCausaContato")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("TipoCausaContato");

                    b.HasKey("Id")
                        .HasName("PK_SiteContato");

                    b.ToTable("SiteContato", (string)null);
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.AdvogadoEspecialidade", b =>
                {
                    b.HasOne("JustoNovo.Domain.ProcessosEntidades.Advogado", "Advogado")
                        .WithMany("AdvogadosEspecialidades")
                        .HasForeignKey("AdvogadoId");

                    b.Navigation("Advogado");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Cliente", b =>
                {
                    b.HasOne("JustoNovo.Domain.ProcessosEntidades.Endereco", "Endereco")
                        .WithOne("EnderecoCliente")
                        .HasForeignKey("JustoNovo.Domain.ProcessosEntidades.Cliente", "EnderecoId");

                    b.OwnsOne("JustoNovo.Domain.ProcessosEntidades.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Cpf");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Polo", b =>
                {
                    b.HasOne("JustoNovo.Domain.ProcessosEntidades.Processo", "Processo")
                        .WithMany("PoloPartes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Processo", b =>
                {
                    b.HasOne("JustoNovo.Domain.ProcessosEntidades.Advogado", "Advogado")
                        .WithMany("Processos")
                        .HasForeignKey("AdvogadoId");

                    b.Navigation("Advogado");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.ProcessosAtualizacao", b =>
                {
                    b.HasOne("JustoNovo.Domain.ProcessosEntidades.Processo", "Processo")
                        .WithMany("ProcessosAtualizacoes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.ProcessosCompromissos", b =>
                {
                    b.HasOne("JustoNovo.Domain.ProcessosEntidades.Processo", "Processo")
                        .WithMany("ProcessosCompromissos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Advogado", b =>
                {
                    b.Navigation("AdvogadosEspecialidades");

                    b.Navigation("Processos");
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Endereco", b =>
                {
                    b.Navigation("EnderecoCliente")
                        .IsRequired();
                });

            modelBuilder.Entity("JustoNovo.Domain.ProcessosEntidades.Processo", b =>
                {
                    b.Navigation("PoloPartes");

                    b.Navigation("ProcessosAtualizacoes");

                    b.Navigation("ProcessosCompromissos");
                });
#pragma warning restore 612, 618
        }
    }
}
